In [ ]:
#YOLOv8 Classification
#pip install ultralytics

from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
results = model("https://ultralytics.com/images/bus.jpg" , save=True)  # predict on an image

In [9]:
#YOLOv8 Classification
#pip install ultralytics

from ultralytics import YOLO
import cv2
import numpy as np

model = YOLO('yolov8n.pt')
cap = cv2.VideoCapture(0)
#cap.set(3, 640)
#cap.set(4, 480)

while True:
    ret, img = cap.read()
    if ret == False:
        break
    img = cv2.flip(img, 1)
    # BGR to RGB conversion is performed under the hood
    # see: https://github.com/ultralytics/ultralytics/issues/2575
    results = model.predict(img, conf=0.25)  # Set your desired confidence threshold, default = 0.25

    for result in results:
        for box in result.boxes:
            print(box.xyxy) #box.xyxy.cpu()
            left, top, right, bottom = np.array(box.xyxy, dtype=np.uint16).squeeze() #convert from tensor to list
            print(left, top, right, bottom)
            width = right - left
            height = bottom - top
            center = (left + int((right-left)/2), top + int((bottom-top)/2))
            label = results[0].names[int(box.cls)]
            confidence = float(box.conf.cpu())

            cv2.rectangle(img, (left, top),(right, bottom), (255, 0, 0), 2)
            cv2.putText(img, label+' '+'{:.2f}'.format(confidence),(left+5, bottom-10),cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 1, cv2.LINE_AA)
        
    cv2.imshow('YOLO V8 Detection', img)     
    if cv2.waitKey(1) & 0xFF == 27:
        break

cap.release()
cv2.destroyAllWindows()


0: 480x640 1 person, 38.0ms
Speed: 1.0ms preprocess, 38.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[177.2657, 159.0894, 591.0924, 479.6480]])
177 159 591 479

0: 480x640 1 person, 32.0ms
Speed: 1.0ms preprocess, 32.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[140.3870, 156.7603, 592.6983, 479.5633]])
140 156 592 479

0: 480x640 1 person, 33.0ms
Speed: 1.0ms preprocess, 33.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[141.7195, 159.6053, 592.3116, 479.6305]])
141 159 592 479

0: 480x640 1 person, 32.0ms
Speed: 1.0ms preprocess, 32.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[140.8407, 157.3010, 592.8231, 479.5436]])
140 157 592 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[140.2853, 159.3366, 592.3228, 479.6348]])
140 159 592 479

0: 480x640 1 person, 31.0ms
Speed:

tensor([[118.8751,  89.0897, 624.7831, 479.2569]])
118 89 624 479

0: 480x640 1 person, 32.4ms
Speed: 1.0ms preprocess, 32.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[113.4724,  90.8251, 624.6733, 479.5366]])
113 90 624 479

0: 480x640 1 person, 30.0ms
Speed: 1.0ms preprocess, 30.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[113.5402,  87.6634, 627.9163, 479.5248]])
113 87 627 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[112.0322,  85.1532, 631.1954, 479.5219]])
112 85 631 479

0: 480x640 1 person, 30.4ms
Speed: 1.0ms preprocess, 30.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[110.2853,  83.5169, 628.0208, 479.5496]])
110 83 628 479

0: 480x640 1 person, 31.4ms
Speed: 1.0ms preprocess, 31.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[104.5590,  70.3243, 629.0583, 4

tensor([[166.8682,  76.2908, 640.0000, 478.3976]])
166 76 640 478

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[168.5504,  78.4213, 639.9768, 479.2727]])
168 78 639 479

0: 480x640 1 person, 31.0ms
Speed: 1.3ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[169.6093,  80.3536, 639.8246, 479.3279]])
169 80 639 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[169.1239,  81.2727, 640.0000, 479.2978]])
169 81 640 479

0: 480x640 1 person, 31.5ms
Speed: 1.0ms preprocess, 31.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[167.9974,  80.9865, 639.7960, 479.1515]])
167 80 639 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[158.5546,  75.8441, 640.0000, 4

tensor([[ 65.4907,  75.5754, 597.9272, 479.8044]])
65 75 597 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[ 65.9044,  77.4994, 587.3499, 479.9113]])
65 77 587 479

0: 480x640 1 person, 31.5ms
Speed: 1.0ms preprocess, 31.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[ 71.5518,  76.1902, 590.7336, 479.6108]])
71 76 590 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[ 72.0480,  75.4108, 591.2158, 479.6440]])
72 75 591 479

0: 480x640 1 person, 31.4ms
Speed: 1.0ms preprocess, 31.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[ 74.4687,  74.7580, 593.3213, 479.6492]])
74 74 593 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[ 74.4189,  75.1162, 594.9906, 479.67

tensor([[126.7850,  78.4839, 640.0000, 479.3945]])
126 78 640 479

0: 480x640 1 person, 31.5ms
Speed: 1.0ms preprocess, 31.5ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[127.8248,  80.5657, 639.8925, 479.1683]])
127 80 639 479

0: 480x640 1 person, 31.5ms
Speed: 1.0ms preprocess, 31.5ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[128.1812,  78.9709, 639.5884, 479.2272]])
128 78 639 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[128.6344,  79.6792, 639.7150, 479.1816]])
128 79 639 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[127.8719,  80.8883, 639.7230, 479.2421]])
127 80 639 479

0: 480x640 1 person, 31.1ms
Speed: 1.0ms preprocess, 31.1ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[128.0095,  79.4438, 639.8586, 4

tensor([[125.4995,  79.8096, 640.0000, 479.3082]])
125 79 640 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[126.2534,  79.3462, 640.0000, 479.2705]])
126 79 640 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[125.6697,  80.9105, 640.0000, 479.3266]])
125 80 640 479

0: 480x640 1 person, 31.5ms
Speed: 1.0ms preprocess, 31.5ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[123.6727,  81.0953, 640.0000, 479.2190]])
123 81 640 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[123.4361,  84.2733, 640.0000, 479.3193]])
123 84 640 479

0: 480x640 1 person, 31.4ms
Speed: 1.0ms preprocess, 31.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[118.4885,  77.5793, 639.9401, 4

tensor([[138.8043,  77.1303, 639.6150, 479.3599]])
138 77 639 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[139.6634,  76.8341, 639.6298, 479.3384]])
139 76 639 479

0: 480x640 1 person, 31.6ms
Speed: 1.0ms preprocess, 31.6ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[138.2255,  73.7700, 639.7015, 479.2895]])
138 73 639 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[137.9680,  76.8549, 639.9320, 479.3433]])
137 76 639 479

0: 480x640 1 person, 31.5ms
Speed: 1.0ms preprocess, 31.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[138.3594,  77.0871, 639.8845, 479.4322]])
138 77 639 479

0: 480x640 1 person, 31.0ms
Speed: 1.0ms preprocess, 31.0ms inference, 0.0ms postprocess per image at shape (1, 3, 480, 640)
tensor([[138.6158,  78.3274, 639.5777, 4

## Practice : People detector and analyzer
1. Input images from wiiplay.mp4 with frame number between 41000 and 44000.
2. Use YOLOv8 to detect people, mark as red rectangle, and count how many persons in each frame. (hint: check label == 'person')
3. Try to find out which frame contains the most number of persons. (print the number of persons on the upper-left corner)
4. (optional) Try to find out which frame containes the largest person. (print the size of its bounding box on the upper-left corner)
5. (optional) Try to find out which frame containes the smallest person. (print the size of its bounding box on the upper-left corner)
6. Show the three output frames you found.
7. Verify the correctness of your output, then adjust the desired confidence threshold for improvement. 
8. Upload your Jupyter code file (*.ipynb)